### ISSUE TITLE
Calls to uri.authenticate() can fail with bad mac error when using expressjs sub apps

### ISSUE THREAD

**Issue by mjy78** [hueniverse/hawk#201] opened 2016-11-09 06:15 UTC
If an expressjs app is using sub apps that make calls to uri.authenticate() then the req.url extracted from the node req object (in utils.parseRequest) does not contain the full url. 

For example you have an app that (via app.use()) includes routes for an admin module:
`app.use('/admin', require('./modules/admin'))
`
and the admin module has a route for downloading a file:
`router.get('/download-file/:filename', middlewareToAuthenticateMac, callThisControllerOnceMacOk);`

and in your middlewareToAuthenticateMac you make a call to hawk.uri.authenticate(req, ...) then internally when the authenticate method calls utils.parseRequest, the req.url property does not include the full path of the call. In the example above it would contain only '/download-file/filename' instead of '/admin/download-file/filename'.

In express (in v4 at least I think) the req.url may not contain the full url as it can be rewritten for internal routing. 

Changing the util.parseRequest method to try to access the 'originalUrl' property first seems to fix the problem...

`exports.parseRequest = function (req, options) {

    if (!req.headers) {
        return req;
    }

    // Obtain host and port information

    let host;
    if (!options.host ||
        !options.port) {

        host = exports.parseHost(req, options.hostHeaderName);
        if (!host) {
            return new Error('Invalid Host header');
        }
    }

    const request = {
        method: req.method,
        url: req.originalUrl || req.url,
        host: options.host || host.name,
        port: options.port || host.port,
        authorization: req.headers.authorization,
        contentType: req.headers['content-type'] || ''
    };

    return request;
};`

**Comment by mjy78** [comment] 2016-11-09 22:48
It looks like @FabriceMonnereau has added a "basePath" option in the fork here:
https://github.com/haxesysteme/hawk

This appears to be a better approach as it avoids introducing a breaking change to existing consumers of the project.

**Comment by euvl** [comment] 2016-11-28 03:30
@mjy78 thanks mate, it took me 3hrs to track where the problem is :)

**Comment by hueniverse** [comment] 2016-11-28 23:32
Didn't realize express was this bad...

I am open to consider a configuration option to work around it as long as it is super simple and fully tested. I don't use express and won't merge it if I need to do any work on it... :-)

**Comment by Dreyer** [comment] 2016-11-30 18:47
What version of Express are you using? I'm not sure this is a Hawk issue so much as something that should be resolved by extending Express with middleware.

I've been using Hawk v6.x with Express v4.x by means of a middleware to handle the situation you're talking about to sign/verify requests with an Authorization header and using bewits.

**Comment by mjy78** [comment] 2016-11-30 23:07
@Dreyer I'm using express 4.13.3. The express documentation for [req.originalUrl](http://expressjs.com/en/4x/api.html#req.originalUrl) seems to indicate that it's acceptable that the req.url could be rewritten (in my case due to app.use() with sub-apps).

**Comment by hueniverse** [comment] 2016-12-01 00:40
If express is preserving the original raw uri, you should wrap hawk and use that via the alternative (non request object) interface. I would prefer not to add more config options if we don't have to.

**Comment by mjy78** [comment] 2016-12-01 01:04
That sounds reasonable. 

So just to confirm, you are saying that instead of passing the node/express req object into hawk.uri.authenticate(), I should instead build a custom request object and manually assign the url property of this object the original (originalUrl) raw url from the express req object?

Something like...

```
var request = {
    method: req.method,
    url: req.originalUrl,
    host: req.host,
    port: req.port,
    authorization: req.authorization
}

hawk.uri.authenticate(request, ... );
```

**Comment by hueniverse** [comment] 2016-12-01 01:18
Yep. Probably missing `headers` somewhere in there.

**Comment by mjy78** [comment] 2016-12-01 01:21
Yes. Will actually be something like...

```
  var request = {
    method: req.method,
    url: req.originalUrl,
    headers: {
      authorization: req.headers.authorization,
      'content-type': req.headers['content-type'] || '' 
    }
  };

  hawk.uri.authenticate(request, ... );
```

**Comment by Dreyer** [comment] 2017-02-03 16:24
For what it's worth, I've got round to uploading the middleware I'm using to glue Hawk and Express together: [Dreyer/express-hawk](https://github.com/Dreyer/express-hawk)

**Closed** 2017-05-27 22:16 UTC
Labels: help wanted, request
